# Generated by Django 4.2.4 on 2024-12-21 16:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CabClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cab_class", models.CharField(max_length=200, unique=True)),
                ("icon", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CabType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cab_type", models.CharField(max_length=74, unique=True)),
                ("icon", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleMaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("maker", models.CharField(max_length=200, unique=True)),
                ("icon", models.TextField(blank=True, null=True)),
                (
                    "cab_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cabs.cabtype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model", models.CharField(max_length=200, unique=True)),
                ("model_image", models.TextField(blank=True, null=True)),
                (
                    "cabclass",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cabs.cabclass",
                    ),
                ),
                (
                    "cabtype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cabs.cabtype",
                    ),
                ),
                (
                    "maker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cabs.vehiclemaker",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number_plate", models.CharField(max_length=74, unique=True)),
                (
                    "vehicle_photo",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                (
                    "vehicle_certiifcate",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "last_latitude",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "last_longitude",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "cab_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="cabs.cabclass",
                    ),
                ),
                (
                    "cab_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="cabs.cabtype",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="accounts.driver",
                    ),
                ),
                (
                    "maker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="cabs.vehiclemaker",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="cabs.vehiclemodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="cabclass",
            name="cab_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="cabs.cabtype"
            ),
        ),
        migrations.CreateModel(
            name="CabBookingPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_fare",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="base fare for per kms",
                    ),
                ),
                (
                    "waiting_fare_per_minute",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="waiting fare per minute",
                    ),
                ),
                (
                    "cab_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cabs.cabclass"
                    ),
                ),
            ],
            options={
                "db_table": "cabbookingprice",
            },
        ),
    ]
