# Generated by Django 4.2.4 on 2023-08-18 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CabType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab_type', models.CharField(max_length=74)),
                ('cab_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cabs.cabtype')),
            ],
        ),
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=74, unique=True)),
                ('reg_no', models.CharField(max_length=74, unique=True)),
                ('_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabs.cabtype')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
