# Generated by Django 5.1.4 on 2025-02-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cabbookingprice",
            name="scheduled_trip_fare_precentage",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
