# Generated by Django 4.2.4 on 2023-08-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0002_cabclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='cab',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cab',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cab',
            name='last_location',
            field=models.CharField(blank=True, max_length=174, null=True),
        ),
    ]
