# Generated by Django 5.1.4 on 2025-04-14 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabs", "0004_alter_cabclass_icon_alter_cabtype_icon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cabclass",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name="cabtype",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name="vehiclemaker",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name="vehiclemodel",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
