# Generated by Django 4.2.4 on 2023-08-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0005_cabclass_created_at_cabclass_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='insurance_certiifcate_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_certiifcate_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
