# Generated by Django 4.2.4 on 2023-08-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0006_vehicle_insurance_certiifcate_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
