# Generated by Django 4.2.4 on 2023-08-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0008_cabclass_updated_at_cabtype_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='insurance_certiifcate_1',
            new_name='addtional_document',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='insurance_certiifcate_2',
            new_name='insurance_certiifcate',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='insurance_certiifcate_3',
            new_name='mot_certiifcate',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_certiifcate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
