# Generated by Django 4.2.4 on 2023-09-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0009_rename_insurance_certiifcate_1_vehicle_addtional_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='back',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='back_head_light',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='front',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='front_head_light',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='inside_driver_seat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='inside_passanger_seat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='left',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='right',
            field=models.TextField(blank=True, null=True),
        ),
    ]
