# Generated by Django 4.2.4 on 2023-09-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0010_vehicle_back_vehicle_back_head_light_vehicle_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='pollution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='sound',
            field=models.TextField(blank=True, null=True),
        ),
    ]
