# Generated by Django 4.2.4 on 2023-09-22 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0011_vehicle_pollution_vehicle_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemaker',
            name='cab_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cabs.cabtype'),
            preserve_default=False,
        ),
    ]
