# Generated by Django 4.2.4 on 2023-09-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0012_vehiclemaker_cab_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabclass',
            name='icon',
            field=models.CharField(default='car-icon', max_length=74),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cabclass',
            name='price',
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
    ]
