# Generated by Django 4.2.4 on 2023-11-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0014_remove_cabclass_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='model_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehiclemodel/'),
        ),
    ]
