# Generated by Django 4.2.4 on 2023-11-13 11:13

import cabs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0015_vehiclemodel_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='model_image',
            field=models.ImageField(blank=True, null=True, upload_to=cabs.models.vehicle_model_directory_path),
        ),
    ]
