# Generated by Django 4.2.4 on 2024-06-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0017_alter_cabclass_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='addtional_document',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insurance_certiifcate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='mot_certiifcate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='pollution',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='registration_certiifcate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='sound',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_certiifcate',
            field=models.JSONField(default=None),
        ),
    ]
