# Generated by Django 4.2.4 on 2024-06-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0018_remove_vehicle_addtional_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_certiifcate',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
