# Generated by Django 4.2.4 on 2024-06-28 16:27

import cabs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0019_alter_vehicle_vehicle_certiifcate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabclass',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=cabs.models.vehicle_model_directory_path),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='model_image',
            field=models.FileField(blank=True, null=True, upload_to=cabs.models.vehicle_model_directory_path),
        ),
    ]
