# Generated by Django 4.2.4 on 2024-07-02 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0020_alter_cabclass_icon_alter_vehiclemodel_model_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabBookingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='base fare for per kms')),
                ('extra_km_fare', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='extra km fare')),
                ('waiting_fare_per_minute', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='waiting fare per minute')),
                ('cab_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabs.cabclass')),
            ],
            options={
                'db_table': 'cabbookingprice',
            },
        ),
    ]
