# Generated by Django 4.2.4 on 2024-07-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0021_cabbookingprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='last_location',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='cabclass',
            name='cab_class',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cabtype',
            name='cab_type',
            field=models.CharField(max_length=74, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiclemaker',
            name='maker',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='model',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
