# Generated by Django 4.2.4 on 2024-07-24 07:32

import cabs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0022_remove_vehicle_last_location_vehicle_last_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabclass',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=cabs.models.vehicle_class_directory_path),
        ),
    ]
