# Generated by Django 4.2.4 on 2024-07-31 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0024_remove_vehicle_back_remove_vehicle_back_head_light_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemaker',
            name='cab_type',
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='cabclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cabs.cabclass'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='cabtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cabs.cabtype'),
        ),
    ]
