# Generated by Django 4.2.4 on 2024-08-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0025_remove_vehiclemaker_cab_type_vehiclemodel_cabclass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabbookingprice',
            name='extra_km_fare',
        ),
    ]
