# Generated by Django 4.2.4 on 2024-08-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0026_remove_cabbookingprice_extra_km_fare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='last_latitude',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='last_longitude',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=21, null=True),
        ),
    ]
