# Generated by Django 4.2.4 on 2024-08-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0027_alter_vehicle_last_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='last_latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='last_longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
