# Generated by Django 4.2.4 on 2024-08-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0028_alter_vehicle_last_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabclass',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cabtype',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemaker',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='model_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
