# Generated by Django 4.2.4 on 2024-09-15 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0029_alter_cabclass_icon_alter_cabtype_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemaker',
            name='cab_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cabs.cabtype'),
        ),
    ]
