# Generated by Django 4.2.4 on 2024-10-04 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0030_vehiclemaker_cab_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabclass',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 7, 38, 56, 16167, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cabtype',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 7, 38, 56, 16167, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 7, 38, 56, 16167, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vehiclemaker',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 7, 38, 56, 16167, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 7, 38, 56, 16167, tzinfo=datetime.timezone.utc)),
        ),
    ]
