# Generated by Django 4.2.4 on 2024-12-21 16:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill_Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="usd", max_length=10)),
                (
                    "payment_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("payment_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PAID", "PAID"),
                            ("PENDING", "PENDING"),
                            ("FAILED", "FAILED"),
                            ("REFUNDED", "REFUNDED"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_receive_payment",
                        to="accounts.driver",
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passenger_pay_ride_charge",
                        to="accounts.customer",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="trips.trip"
                    ),
                ),
            ],
            options={
                "db_table": "bill_payment",
            },
        ),
    ]
