# Generated by Django 4.2.4 on 2024-07-22 13:56

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0012_delete_driverpricingratio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('payment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('PAID', 'PAID'), ('PENDING', 'PENDING'), ('FAILED', 'FAILED'), ('REFUNDED', 'REFUNDED')], max_length=15)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
