# Generated by Django 4.2.4 on 2024-09-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_alter_trip_distance'),
        ('accounts', '0038_user_rejection_reason'),
        ('payment', '0002_payment_driver_payment_passenger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Bill_Payment',
        ),
        migrations.AlterModelTable(
            name='bill_payment',
            table='bill_payment',
        ),
    ]
