# Generated by Django 5.1.4 on 2025-04-14 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="o2oroom",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
