# Generated by Django 4.2.4 on 2023-10-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_content_message_message_o2oroom_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='o2oroom',
            name='room_name',
        ),
        migrations.AddField(
            model_name='o2oroom',
            name='room',
            field=models.CharField(default=None, max_length=18),
        ),
    ]
