# Generated by Django 4.2.4 on 2023-10-12 10:20

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_o2oroom_room_name_o2oroom_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o2oroom',
            name='room',
            field=models.CharField(default=chat.models.generate_room_name, max_length=18),
        ),
    ]
