# Generated by Django 4.2.4 on 2023-10-15 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_alter_o2oroom_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='o2oroom',
            name='sender_receiver',
            field=models.ManyToManyField(related_name='sender_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
