# Generated by Django 4.2.4 on 2023-10-15 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_o2oroom_sender_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o2oroom',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='o2oroom',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='o2oroom',
            name='sender_receiver',
        ),
        migrations.AddField(
            model_name='o2oroom',
            name='sender_receiver',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
