# Generated by Django 4.2.4 on 2023-10-15 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_o2oroom_receiver_alter_o2oroom_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='o2oroom',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='o2oroom',
            name='sender',
        ),
    ]
