# Generated by Django 4.2.4 on 2024-10-04 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_o2oroom_receiver_remove_o2oroom_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o2oroom',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 7, 38, 56, 16167, tzinfo=datetime.timezone.utc)),
        ),
    ]
