# Generated by Django 5.1.4 on 2025-02-02 16:26

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="file",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 2, 16, 26, 43, 301190, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo_upload",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
