# Generated by Django 5.1.4 on 2025-02-17 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_address_user_country_user_landmark_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 17, 10, 50, 26, 575936, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo_upload",
            field=models.CharField(blank=True, null=True),
        ),
    ]
