# Generated by Django 5.1.4 on 2025-04-14 05:45

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_fileupload_file_alter_user_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 14, 5, 45, 39, 406965, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date joined",
            ),
        ),
    ]
