# Generated by Django 4.2.4 on 2023-08-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreferral',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userreferral',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
