# Generated by Django 4.2.4 on 2023-08-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customer_driver_user_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('DRIVER', 'driver'), ('CUSTOMER', 'customer')], default='CUSTOMER', max_length=11),
        ),
    ]
