# Generated by Django 4.2.4 on 2023-08-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_phoneverify_customerphoneverify_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='license_upload_back',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='myride_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_policy',
            field=models.BooleanField(default=False),
        ),
    ]
