# Generated by Django 4.2.4 on 2023-08-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_license_upload_back_user_myride_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driver_duty',
            field=models.BooleanField(default=True),
        ),
    ]
