# Generated by Django 4.2.4 on 2023-09-05 12:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_carowner_user_is_carowner_alter_user_driver_duty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='phonne',
            field=models.CharField(default=1, max_length=74),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to=accounts.models.user_directory_path),
        ),
    ]
