# Generated by Django 4.2.4 on 2023-10-04 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carownerphoneverify',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.driver'),
        ),
        migrations.AlterField(
            model_name='customerphoneverify',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='driverphoneverify',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.driver'),
        ),
    ]
