# Generated by Django 4.2.4 on 2023-11-17 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carownerphoneverify',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.carowner'),
        ),
    ]
