# Generated by Django 4.2.4 on 2024-06-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_carownerphoneverify_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carownerphoneverify',
            name='user',
        ),
        migrations.DeleteModel(
            name='CarOwner',
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.RemoveField(
            model_name='user',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='aadhar_upload_back',
        ),
        migrations.RemoveField(
            model_name='user',
            name='aadhar_upload_front',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_carowner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_driver',
        ),
        migrations.RemoveField(
            model_name='user',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='license_upload_back',
        ),
        migrations.RemoveField(
            model_name='user',
            name='license_upload_front',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pan_upload',
        ),
        migrations.AddField(
            model_name='user',
            name='user_doccument',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('DRIVER', 'driver'), ('CUSTOMER', 'customer'), ('ADMIN', 'admin')], default='CUSTOMER', max_length=11),
        ),
        migrations.DeleteModel(
            name='CarOwnerPhoneVerify',
        ),
    ]
