# Generated by Django 4.2.4 on 2024-06-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_carownerphoneverify_user_delete_carowner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_doccument',
            new_name='user_document',
        ),
    ]
