# Generated by Django 4.2.4 on 2024-06-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_rename_user_document_user_user_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_doc',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
