# Generated by Django 4.2.4 on 2024-06-28 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('account_number', models.CharField(max_length=25, unique=True)),
                ('ifsc_code', models.CharField(max_length=35, unique=True)),
                ('bank_name', models.CharField(max_length=200, unique=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backaccount', to='accounts.driver')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
