# Generated by Django 4.2.4 on 2024-08-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_currentlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Rejected', 'Rejected'), ('Block', 'Block')], default='Pending', max_length=74),
        ),
    ]
