# Generated by Django 4.2.4 on 2024-09-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_user_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
