# Generated by Django 4.2.4 on 2024-09-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_bankaccount_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='ifsc_code',
            new_name='swift_code',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='routing_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='routing number'),
        ),
    ]
