# Generated by Django 5.1.4 on 2025-04-14 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_driversupport_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customersupport",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 14, 5, 45, 39, 427963, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="driversupport",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 14, 5, 45, 39, 427963, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
