# Generated by Django 4.2.4 on 2024-10-04 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_customersupport_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupport',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 16, 17, 16, 347626, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='driversupport',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 16, 17, 16, 345631, tzinfo=datetime.timezone.utc)),
        ),
    ]
