# Generated by Django 4.2.4 on 2024-10-04 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soshelprequest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 7, 38, 56, 120450, tzinfo=datetime.timezone.utc)),
        ),
    ]
