# Generated by Django 5.1.4 on 2025-02-02 18:05

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SOSMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="soshelprequest",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 2, 18, 5, 30, 847960, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
