# Generated by Django 5.1.4 on 2025-04-14 05:45

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sos", "0002_sosmessage_alter_soshelprequest_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soshelprequest",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 14, 5, 45, 39, 426964, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="sosmessage",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
