# Generated by Django 4.2.4 on 2024-10-04 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0002_alter_soshelprequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='soshelprequest',
            name='last_latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='soshelprequest',
            name='last_longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='soshelprequest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 13, 59, 5, 555256, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='soshelprequest',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
