# Generated by Django 4.2.4 on 2024-10-04 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0004_alter_soshelprequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soshelprequest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 16, 17, 16, 341271, tzinfo=datetime.timezone.utc)),
        ),
    ]
