# Generated by Django 4.2.4 on 2024-09-22 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_transaction_remake_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='remake',
            new_name='remark',
        ),
    ]
