# Generated by Django 4.2.4 on 2024-10-04 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_transaction_transaction_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 7, 38, 56, 94363, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 7, 38, 56, 99418, tzinfo=datetime.timezone.utc)),
        ),
    ]
