# Generated by Django 4.2.4 on 2024-10-04 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_alter_transaction_date_alter_wallet_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 14, 0, 41, 861570, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 14, 0, 41, 859534, tzinfo=datetime.timezone.utc)),
        ),
    ]
