# Generated by Django 4.2.4 on 2024-10-07 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0009_transaction_receiver_transaction_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 8, 22, 35, 900118, tzinfo=datetime.timezone.utc)),
        ),
    ]
