# Generated by Django 4.2.4 on 2024-10-07 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0010_alter_wallet_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('EXPENSE', 'Expense'), ('INCOME', 'Income')], max_length=80),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 12, 4, 4, 270645, tzinfo=datetime.timezone.utc)),
        ),
    ]
