# Generated by Django 4.2.4 on 2024-10-15 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0011_alter_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 15, 7, 2, 54, 198873, tzinfo=datetime.timezone.utc)),
        ),
    ]
