# Generated by Django 5.1.4 on 2025-02-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("couponcode", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="use_count",
            field=models.IntegerField(default=0),
        ),
    ]
