# Generated by Django 4.2.4 on 2024-12-21 16:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("cabs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(max_length=500)),
                ("days", models.PositiveIntegerField(default=0)),
                ("price", models.PositiveIntegerField(default=0)),
                ("discount", models.PositiveIntegerField(default=0)),
                ("original_price", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            12,
                            21,
                            16,
                            54,
                            2,
                            577017,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_plans",
                        to="cabs.cabclass",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_plan",
            },
        ),
        migrations.CreateModel(
            name="Subscriptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pay_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("subcribe_date", models.DateTimeField()),
                ("expire_date", models.DateTimeField()),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PAID", "PAID"),
                            ("PENDING", "PENDING"),
                            ("FAILED", "FAILED"),
                            ("REFUNDED", "REFUNDED"),
                        ],
                        max_length=15,
                    ),
                ),
                ("number_of_time_subscribe", models.IntegerField(default=0)),
                (
                    "payment_id",
                    models.CharField(blank=True, default=" ", max_length=55, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            12,
                            21,
                            16,
                            54,
                            2,
                            577017,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.driver",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
            },
        ),
        migrations.CreateModel(
            name="Subscription_Logs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pay_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("subcribe_date", models.DateTimeField()),
                ("expire_date", models.DateTimeField()),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PAID", "Paid"),
                            ("PENDING", "Pending"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True, default=None, max_length=55, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            12,
                            21,
                            16,
                            54,
                            2,
                            578152,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.driver",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_logs",
            },
        ),
    ]
