# Generated by Django 4.2.4 on 2024-07-17 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='payment_getway_name',
        ),
        migrations.RemoveField(
            model_name='subscriptions_logs',
            name='number_of_time_subscribe',
        ),
        migrations.RemoveField(
            model_name='subscriptions_logs',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='subscriptions_logs',
            name='payment_getway_name',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
