# Generated by Django 4.2.4 on 2024-08-06 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionplan',
            unique_together=set(),
        ),
    ]
