# Generated by Django 4.2.4 on 2024-08-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscriptionplan_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_logs',
            name='payment_id',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('PENDING', 'PENDING'), ('FAILED', 'FAILED'), ('REFUNDED', 'REFUNDED')], max_length=15),
        ),
    ]
