# Generated by Django 4.2.4 on 2024-07-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_subscription_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
