# Generated by Django 4.2.4 on 2024-10-04 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscription_logs_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription_logs',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='subscription_logs',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 7, 38, 56, 114937, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 7, 38, 56, 110887, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 7, 38, 56, 112943, tzinfo=datetime.timezone.utc)),
        ),
    ]
