# Generated by Django 4.2.4 on 2024-07-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscriptionplan_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='number_of_rides',
            new_name='ride_numbers',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
