# Generated by Django 4.2.4 on 2024-10-04 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_subscription_logs_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_logs',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 14, 0, 41, 866569, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 14, 0, 41, 865548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 14, 0, 41, 866569, tzinfo=datetime.timezone.utc)),
        ),
    ]
