# Generated by Django 4.2.4 on 2024-10-04 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_subscription_logs_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_logs',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 16, 17, 16, 335317, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 16, 17, 16, 330264, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 16, 17, 16, 333317, tzinfo=datetime.timezone.utc)),
        ),
    ]
