# Generated by Django 4.2.4 on 2023-11-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabbookingpricesetting',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='vehiclerentepricesetting',
            name='model_name',
        ),
    ]
