# Generated by Django 4.2.4 on 2023-11-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_remove_cabbookingpricesetting_model_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CabBookingPriceSetting',
        ),
    ]
