# Generated by Django 4.2.4 on 2023-11-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0003_delete_cabbookingpricesetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleRentePriceSetting',
        ),
    ]
