# Generated by Django 4.2.4 on 2024-06-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_api', '0004_delete_vehiclerentepricesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocumentField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=500, unique=True)),
                ('textfield', models.BooleanField(default=False)),
                ('filefield', models.BooleanField(default=True)),
                ('frontback', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCertificateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=500, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
