# Generated by Django 4.2.4 on 2024-07-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0007_rename_frontback_userdocumentfield_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocumentfield',
            name='suggetions_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
