# Generated by Django 4.2.4 on 2024-07-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0009_driverfeedbackpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePhotoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=500, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
