# Generated by Django 4.2.4 on 2024-10-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerreferral',
            old_name='reward_amount',
            new_name='referred_reward_amount',
        ),
        migrations.AddField(
            model_name='customerreferral',
            name='referrer_reward_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
