# Generated by Django 4.2.4 on 2023-08-24 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabs', '0008_cabclass_updated_at_cabtype_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[(1, 'ACCEPTED'), (2, 'REJECTED'), (3, 'BOOKED'), (4, 'CANCELLED'), (5, 'ON_TRIP'), (6, 'COMPLETED')], max_length=74, null=True)),
                ('source', models.CharField(max_length=74)),
                ('destination', models.CharField(max_length=74)),
                ('cab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='cabs.vehicle')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cutomer_trips', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('star', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
