# Generated by Django 4.2.4 on 2024-12-21 16:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_api", "0001_initial"),
        ("cabs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REQUESTED", "REQUESTED"),
                            ("ACCEPTED", "ACCEPTED"),
                            ("REJECTED", "REJECTED"),
                            ("BOOKED", "BOOKED"),
                            ("CANCELLED", "CANCELLED"),
                            ("ON_TRIP", "ON_TRIP"),
                            ("COMPLETED", "COMPLETED"),
                        ],
                        max_length=74,
                        null=True,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=5000, null=True)),
                (
                    "destination",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                (
                    "pickup_latitude",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "pickup_longitude",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "dropup_latitude",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "dropup_longitude",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "distance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("time", models.CharField(blank=True, max_length=74, null=True)),
                ("otp_count", models.PositiveIntegerField(default=1)),
                ("order_id", models.TextField(blank=True, max_length=74, null=True)),
                (
                    "rent_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("scheduled_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "cancel_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("otp", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "payment_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("waiting_time", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "waiting_charge",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_fare",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "driver_arrived_at_pickup_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("ride_start_time", models.DateTimeField(blank=True, null=True)),
                ("ride_end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "cab",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="cabs.vehicle",
                    ),
                ),
                (
                    "canceled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="canceled_trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cutomer_trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="driver_trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ride_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cabs.cabclass"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TripRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("star", models.FloatField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cutomer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="driver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feedbacksetting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="admin_api.feedbacksetting",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="trips.trip"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
