# Generated by Django 5.1.4 on 2025-02-16 10:31

import utility.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_alter_trip_ride_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="trip_id",
            field=models.CharField(
                blank=True,
                default=utility.util.generate_six_digit_uuid,
                max_length=500,
                null=True,
            ),
        ),
    ]
