# Generated by Django 4.2.4 on 2023-08-24 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0009_rename_insurance_certiifcate_1_vehicle_addtional_document_and_more'),
        ('trips', '0002_alter_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='otp_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trip',
            name='ride_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cabs.cabclass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='timing',
            field=models.CharField(blank=True, max_length=74, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(blank=True, max_length=74, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='source',
            field=models.CharField(blank=True, max_length=74, null=True),
        ),
    ]
