# Generated by Django 5.1.4 on 2025-04-14 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_trip_trip_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name="triprating",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
