# Generated by Django 5.1.4 on 2025-04-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0004_alter_trip_created_at_alter_triprating_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PickupRadius",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("radius", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
