# Generated by Django 4.2.4 on 2023-11-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_trip_cab'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPricingRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ratio', models.FloatField(verbose_name='Ratio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
