# Generated by Django 5.1.4 on 2025-04-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0005_pickupradius"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="coupon_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
