# Generated by Django 4.2.4 on 2024-07-15 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0009_trip_scheduled_date_trip_scheduled_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(blank=True, choices=[('REQUESTED', 'REQUESTED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('BOOKED', 'BOOKED'), ('CANCELLED', 'CANCELLED'), ('ON_TRIP', 'ON_TRIP'), ('COMPLETED', 'COMPLETED')], max_length=74, null=True),
        ),
    ]
