# Generated by Django 4.2.4 on 2024-08-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_delete_driverpricingratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='dropup_latitude',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=21, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='dropup_longitude',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=21, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=21, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=21, null=True),
        ),
    ]
