# Generated by Django 4.2.4 on 2024-08-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_trip_dropup_latitude_trip_dropup_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='dropup_latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropup_longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
