# Generated by Django 4.2.4 on 2024-08-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_alter_trip_dropup_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
