# Generated by Django 4.2.4 on 2024-09-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_alter_trip_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='source',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
