# Generated by Django 4.2.4 on 2024-10-07 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0021_trip_driver_arrived_at_pickup_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 8, 20, 21, 941285, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='triprating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 8, 20, 21, 941285, tzinfo=datetime.timezone.utc)),
        ),
    ]
