# Generated by Django 5.1.4 on 2025-02-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drivernotification",
            name="banner",
            field=models.CharField(blank=True, null=True),
        ),
    ]
