# Generated by Django 5.1.4 on 2025-04-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_notificationtemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationtemplate",
            name="type",
            field=models.CharField(max_length=50),
        ),
    ]
